/*
 * Copyright (c) 2017 The University of Manchester
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*! \file
 *
 * \brief Connection Generator interface
 *
 */

#include <stdint.h>
#include <common-typedefs.h>

#include "param_generator.h"
#include "matrix_generator.h"

/**
 * \brief Connection generator "object"
 */
typedef struct connection_generator *connection_generator_t;

/**
 * \brief Initialise a specific connection generator
 * \param[in] hash: The identifier of the generator to initialise
 * \param[in,out] region: The address to read data from; updated to position
 *                        after data has been read
 * \return An initialised connection generator that can be used with other
 *         functions, or NULL if it couldn't be initialised for any reason
 */
connection_generator_t connection_generator_init(
        uint32_t hash, void **region);

/**
 * \brief Finish with a connection generator
 * \param[in] generator: The generator to free
 */
void connection_generator_free(connection_generator_t generator);

/**
 * \brief Generate connections with a connection generator
 * \param[in] generator: The generator to use to generate connections
 * \param[in] pre_lo: The lowest pre-population index that should be generated
 * \param[in] pre_hi: The highest pre-population index that should be generated
 * \param[in] post_lo: The lowest post-population index that should be generated
 * \param[in] post_hi: The highest post-population index that should be generated
 * \param[in] pre_slice_start: The start of the slice of the pre-population
 *                             being generated
 * \param[in] pre_slice_count: The number of neurons in the slice of the
 *                             pre-population being generated
 * \param[in] pre_neuron_index: The index of the neuron in the pre-population
 *                              being generated
 * \param[in] post_slice_start: The start of the slice of the post-population
 *                              being generated
 * \param[in] post_slice_count: The number of neurons in the slice of the
 *                              post-population being generated
 * \param[in] weight_scale: The scale to apply to weights generated by the
 *                        weight generator
 * \param[in] timestep_per_delay: The number of timesteps per unit of delay
 * \param[in] weight_generator: The generator to use to generate weights for
 *                           connections
 * \param[in] delay_generator: The generator to use to generate delays for
 *                          connections
 * \param[in] matrix_generator: The generator to use to write generated
 *                         connections to the connection matrix
 * \return True if the generator successfully generated all connections, false if it
 *       failed to generate all connections (e.g. because a parameter generator
 *       failed to generate a parameter for a connection, or because the matrix
 *       generator failed to write a connection).
 */
bool connection_generator_generate(
        connection_generator_t generator,
        uint32_t pre_lo, uint32_t pre_hi,
        uint32_t post_lo, uint32_t post_hi,
        uint32_t pre_slice_start, uint32_t pre_slice_count,
        uint32_t post_slice_start, uint32_t post_slice_count,
        unsigned long accum weight_scale, accum timestep_per_delay,
        param_generator_t weight_generator, param_generator_t delay_generator,
        matrix_generator_t matrix_generator);
