APP = synapse_expander
BUILD_DIR = build/
SOURCES = delay_sender.c rng.c param_generator.c connection_generator.c matrix_generator.c synapse_expander.c

include ../common.mk

CFLAGS += -I$(NEURAL_MODELLING_DIRS)/src
