APP = $(notdir $(CURDIR))$(EXT)
SOURCE_DIR = $(NEURAL_MODELLING_DIRS)/src/neuron
MODEL_OBJS = ../../models/lif_cond_stoc.o ../../static_synapses.o
NEURON_MODEL_H = ../../models/lif_cond_stoc.h
SYNAPSE_SHAPING_H = ../../synapses/exponential_impl.h

include ../Makefile.common