# Copyright (c) 2017-2019 The University of Manchester
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.


APP = $(notdir $(CURDIR))

SYNAPSE_DYNAMICS = $(NEURON_DIR)/synapse/plasticity/stdp/synapse_dynamics_multicomp_Bern.c

TIMING_DEPENDENCE = $(NEURON_DIR)/synapse/plasticity/stdp/timing_dependence/timing_multicomp_Bern.c
TIMING_DEPENDENCE_H = $(NEURON_DIR)/synapse/plasticity/stdp/timing_dependence/timing_multicomp_Bern.h
WEIGHT_DEPENDENCE = $(NEURON_DIR)/synapse/plasticity/stdp/weight_dependence/weight_multiplicative_multicomp_Bern.c
WEIGHT_DEPENDENCE_H = $(NEURON_DIR)/synapse/plasticity/stdp/weight_dependence/weight_multiplicative_multicomp_Bern.h

COMPARTMENT_TYPE_H = $(NEURON_DIR)/synapse/compartment_type/compartment_type_US_model.h

include ../synapse_build.mk