APP = $(notdir $(CURDIR))

OTHER_SOURCES = $(NEURON_DIR)/neuron/models/neuron_model_sinusoid_readout_impl.c
NEURON_IMPL_H = $(NEURON_DIR)/neuron/implementations/neuron_impl_sinusoid_readout.h
SYNAPSE_DYNAMICS = $(NEURON_DIR)/neuron/plasticity/synapse_dynamics_static_impl.c


include ../neural_build.mk
