#!/bin/sh
# Setup script to define the location of the files and the required binaries

set -a

# Define the location of this library
NEURAL_MODELLING_DIRS=$PWD

# Define the location of the app output
APP_OUTPUT_DIR=$NEURAL_MODELLING_DIRS/../spynnaker/pyNN/model_binaries
