APP = $(notdir $(CURDIR))

NEURON_IMPL_H = $(NEURON_DIR)/neuron/implementations/neuron_impl_graz_adaptive.h
SYNAPSE_DYNAMICS = $(NEURON_DIR)/neuron/plasticity/synapse_dynamics_static_impl.c
OTHER_SOURCES = $(NEURON_DIR)/neuron/models/neuron_model_lif_graz_adaptive_impl.c

include ../neural_build.mk
