APP = $(notdir $(CURDIR))
BUILD_DIR = build/

NEURON_MODEL = $(SOURCE_DIR)/neuron/models/neuron_model_HT_impl.c
NEURON_MODEL_H = $(SOURCE_DIR)/neuron/models/neuron_model_HT_impl.h
INPUT_TYPE_H = $(SOURCE_DIR)/neuron/input_types/input_type_HT_conductance.h
THRESHOLD_TYPE_H = $(SOURCE_DIR)/neuron/threshold_types/threshold_type_ht_dynamic.h
SYNAPSE_TYPE_H = $(SOURCE_DIR)/neuron/synapse_types/synapse_types_ht_impl.h
SYNAPSE_DYNAMICS = $(SOURCE_DIR)/neuron/plasticity/synapse_dynamics_static_impl.c
ADDITIONAL_INPUT_H = $(SOURCE_DIR)/neuron/additional_inputs/additional_input_HT_currents_impl.h

include ../common.mk
