var searchData=
[
  ['param_5fgenerator',['param_generator',['../param__generator_8c.html#structparam__generator',1,'']]],
  ['param_5fgenerator_2ec',['param_generator.c',['../param__generator_8c.html',1,'']]],
  ['param_5fgenerator_2eh',['param_generator.h',['../param__generator_8h.html',1,'']]],
  ['param_5fgenerator_5fconstant',['param_generator_constant',['../param__generator__constant_8h.html#structparam__generator__constant',1,'']]],
  ['param_5fgenerator_5fconstant_2eh',['param_generator_constant.h',['../param__generator__constant_8h.html',1,'']]],
  ['param_5fgenerator_5fexponential',['param_generator_exponential',['../param__generator__exponential_8h.html#structparam__generator__exponential',1,'']]],
  ['param_5fgenerator_5fexponential_2eh',['param_generator_exponential.h',['../param__generator__exponential_8h.html',1,'']]],
  ['param_5fgenerator_5fexponential_5fparams',['param_generator_exponential_params',['../param__generator__exponential_8h.html#structparam__generator__exponential__params',1,'']]],
  ['param_5fgenerator_5ffree',['param_generator_free',['../param__generator_8c.html#a20b9f761fb073750e083d131cf49812e',1,'param_generator_free(param_generator_t generator):&#160;param_generator.c'],['../param__generator_8h.html#a20b9f761fb073750e083d131cf49812e',1,'param_generator_free(param_generator_t generator):&#160;param_generator.c']]],
  ['param_5fgenerator_5fgenerate',['param_generator_generate',['../param__generator_8c.html#ae85e6c376848da24228c97141d0d2027',1,'param_generator_generate(param_generator_t generator, uint32_t n_indices, uint32_t pre_neuron_index, uint16_t *indices, accum *values):&#160;param_generator.c'],['../param__generator_8h.html#ae85e6c376848da24228c97141d0d2027',1,'param_generator_generate(param_generator_t generator, uint32_t n_indices, uint32_t pre_neuron_index, uint16_t *indices, accum *values):&#160;param_generator.c']]],
  ['param_5fgenerator_5finfo',['param_generator_info',['../param__generator_8c.html#structparam__generator__info',1,'']]],
  ['param_5fgenerator_5finit',['param_generator_init',['../param__generator_8c.html#ae52a45690f00dfe7384a14645b3512de',1,'param_generator_init(uint32_t hash, address_t *in_region):&#160;param_generator.c'],['../param__generator_8h.html#a7f47aef417cd5ec8cf73a199d71dced2',1,'param_generator_init(uint32_t hash, address_t *region):&#160;param_generator.c']]],
  ['param_5fgenerator_5fkernel',['param_generator_kernel',['../param__generator__kernel_8h.html#structparam__generator__kernel',1,'']]],
  ['param_5fgenerator_5fkernel_2eh',['param_generator_kernel.h',['../param__generator__kernel_8h.html',1,'']]],
  ['param_5fgenerator_5fnormal',['param_generator_normal',['../param__generator__normal_8h.html#structparam__generator__normal',1,'']]],
  ['param_5fgenerator_5fnormal_2eh',['param_generator_normal.h',['../param__generator__normal_8h.html',1,'']]],
  ['param_5fgenerator_5fnormal_5fclipped',['param_generator_normal_clipped',['../param__generator__normal__clipped_8h.html#structparam__generator__normal__clipped',1,'']]],
  ['param_5fgenerator_5fnormal_5fclipped_2eh',['param_generator_normal_clipped.h',['../param__generator__normal__clipped_8h.html',1,'']]],
  ['param_5fgenerator_5fnormal_5fclipped_5fboundary',['param_generator_normal_clipped_boundary',['../param__generator__normal__clipped__to__boundary_8h.html#structparam__generator__normal__clipped__boundary',1,'']]],
  ['param_5fgenerator_5fnormal_5fclipped_5fto_5fboundary_2eh',['param_generator_normal_clipped_to_boundary.h',['../param__generator__normal__clipped__to__boundary_8h.html',1,'']]],
  ['param_5fgenerator_5funiform',['param_generator_uniform',['../param__generator__uniform_8h.html#structparam__generator__uniform',1,'']]],
  ['param_5fgenerator_5funiform_2eh',['param_generator_uniform.h',['../param__generator__uniform_8h.html',1,'']]],
  ['param_5fgenerators',['param_generators',['../param__generator_8c.html#ace4d5547ba44f140e4eb0e5f6fe1a0cc',1,'param_generator.c']]],
  ['params',['params',['../connection__generator__fixed__post_8h.html#a8ed1e9dc57252dc7895cc4922ae38687',1,'fixed_post::params()'],['../spike__source__poisson_8c.html#a5e731a5b624d474b4a71237b20feb29d',1,'params():&#160;spike_source_poisson.c']]],
  ['partner_2eh',['partner.h',['../partner_8h.html',1,'']]],
  ['payload_5ft',['payload_t',['../neuron-typedefs_8h.html#a445182712b36c41ebb26ca639423c0cc',1,'neuron-typedefs.h']]],
  ['plastic_5fsynapse_5ft',['plastic_synapse_t',['../synapse__structure__weight__state__accumulator__window__impl_8h.html#structplastic__synapse__t',1,'plastic_synapse_t'],['../synapse__structure__weight__impl_8h.html#ac4517cb4731427f27418fdf8107fa8c7',1,'plastic_synapse_t():&#160;synapse_structure_weight_impl.h']]],
  ['plastic_5fsynapses',['plastic_synapses',['../synapse__dynamics__stdp__mad__impl_8c.html#a7546f1c4d29b0de40071f49d305ac803',1,'synapse_dynamics_stdp_mad_impl.c']]],
  ['plasticity_5ftrace_5fregion_5fdata_5ft',['plasticity_trace_region_data_t',['../timing__vogels__2011__impl_8h.html#structplasticity__trace__region__data__t',1,'']]],
  ['plasticity_5fupdate_5fsynapse',['plasticity_update_synapse',['../synapse__dynamics__stdp__mad__impl_8c.html#aa195e42fb2e365fe51384e2ef8a95ec8',1,'synapse_dynamics_stdp_mad_impl.c']]],
  ['plasticity_5fweight_5fregion_5fdata_5ft',['plasticity_weight_region_data_t',['../weight__multiplicative__impl_8h.html#structplasticity__weight__region__data__t',1,'']]],
  ['population_5ftable_2eh',['population_table.h',['../population__table_8h.html',1,'']]],
  ['population_5ftable_5fbinary_5fsearch_5fimpl_2ec',['population_table_binary_search_impl.c',['../population__table__binary__search__impl_8c.html',1,'']]],
  ['population_5ftable_5fget_5ffirst_5faddress',['population_table_get_first_address',['../population__table_8h.html#a8bda7c27a3c9d52a2f95c4b6edd58944',1,'population_table_get_first_address(spike_t spike, address_t *row_address, size_t *n_bytes_to_transfer):&#160;population_table_binary_search_impl.c'],['../population__table__binary__search__impl_8c.html#a8bda7c27a3c9d52a2f95c4b6edd58944',1,'population_table_get_first_address(spike_t spike, address_t *row_address, size_t *n_bytes_to_transfer):&#160;population_table_binary_search_impl.c']]],
  ['population_5ftable_5fget_5fnext_5faddress',['population_table_get_next_address',['../population__table_8h.html#a6ab19e2b1b4c0ed25d126d7cd7763ccf',1,'population_table_get_next_address(spike_t *spike, address_t *row_address, size_t *n_bytes_to_transfer):&#160;population_table_binary_search_impl.c'],['../population__table__binary__search__impl_8c.html#a6ab19e2b1b4c0ed25d126d7cd7763ccf',1,'population_table_get_next_address(spike_t *spike, address_t *row_address, size_t *n_bytes_to_transfer):&#160;population_table_binary_search_impl.c']]],
  ['population_5ftable_5finitialise',['population_table_initialise',['../population__table_8h.html#a5f92af4dd47e65504cbbbcb265083196',1,'population_table_initialise(address_t table_address, address_t synapse_rows_address, address_t direct_rows_address, uint32_t *row_max_n_words):&#160;population_table_binary_search_impl.c'],['../population__table__binary__search__impl_8c.html#a5f92af4dd47e65504cbbbcb265083196',1,'population_table_initialise(address_t table_address, address_t synapse_rows_address, address_t direct_rows_address, uint32_t *row_max_n_words):&#160;population_table_binary_search_impl.c']]],
  ['post_5fevent_5fhistory_5ft',['post_event_history_t',['../post__events_8h.html#structpost__event__history__t',1,'']]],
  ['post_5fevent_5fwindow_5ft',['post_event_window_t',['../post__events_8h.html#structpost__event__window__t',1,'']]],
  ['post_5fevents_2eh',['post_events.h',['../post__events_8h.html',1,'']]],
  ['post_5fhi',['post_hi',['../connection__generator__fixed__post_8h.html#a6cc17ffc0a60395bf1697e96ba776d52',1,'fixed_post_params']]],
  ['post_5fin_5fpre_5fworld',['post_in_pre_world',['../common__kernel_8c.html#ae380e1c9722449c4ef92aa2f372bb958',1,'post_in_pre_world(uint16_t in_row, uint16_t in_col, uint16_t start_row, uint16_t start_col, uint16_t step_row, uint16_t step_col, uint16_t *out_row, uint16_t *out_col):&#160;common_kernel.c'],['../common__kernel_8h.html#ae380e1c9722449c4ef92aa2f372bb958',1,'post_in_pre_world(uint16_t in_row, uint16_t in_col, uint16_t start_row, uint16_t start_col, uint16_t step_row, uint16_t step_col, uint16_t *out_row, uint16_t *out_col):&#160;common_kernel.c']]],
  ['post_5flo',['post_lo',['../connection__generator__fixed__post_8h.html#aab9411033f2f70c87c42301cf42fff13',1,'fixed_post_params']]],
  ['post_5flow_5fatom',['post_low_atom',['../sp__structs_8h.html#a45fd8cc8643c292363b09acdb024b5a6',1,'current_state_t']]],
  ['post_5fto_5fpre_5fentry',['post_to_pre_entry',['../sp__structs_8h.html#structpost__to__pre__entry',1,'']]],
  ['post_5ftrace_5ft',['post_trace_t',['../timing__recurrent__pre__stochastic__impl_8h.html#structpost__trace__t',1,'']]],
  ['potential_5fpresynaptic_5fpartner',['potential_presynaptic_partner',['../last__neuron__selection__impl_8h.html#a4869aa919b813c4f93dfca3a23d09159',1,'last_neuron_selection_impl.h']]],
  ['pre_5fevent_5fhistory_5ft',['pre_event_history_t',['../synapse__dynamics__stdp__mad__impl_8c.html#structpre__event__history__t',1,'']]],
  ['pre_5fhi',['pre_hi',['../connection__generator__fixed__post_8h.html#a8804d98e8134803269a43f1b560230fc',1,'fixed_post_params']]],
  ['pre_5fin_5fpost_5fworld',['pre_in_post_world',['../common__kernel_8c.html#a86920262c0a0b97f0cde9a8d05b5e12b',1,'pre_in_post_world(uint16_t in_row, uint16_t in_col, uint16_t start_row, uint16_t start_col, uint16_t step_row, uint16_t step_col, int16_t *out_row, int16_t *out_col):&#160;common_kernel.c'],['../common__kernel_8h.html#a86920262c0a0b97f0cde9a8d05b5e12b',1,'pre_in_post_world(uint16_t in_row, uint16_t in_col, uint16_t start_row, uint16_t start_col, uint16_t step_row, uint16_t step_col, int16_t *out_row, int16_t *out_col):&#160;common_kernel.c']]],
  ['pre_5finfo_5ft',['pre_info_t',['../sp__structs_8h.html#structpre__info__t',1,'']]],
  ['pre_5flo',['pre_lo',['../connection__generator__fixed__post_8h.html#a4eb03d0f757266d94efef44867b62729',1,'fixed_post_params']]],
  ['pre_5fpop_5finfo_5ftable_5ft',['pre_pop_info_table_t',['../sp__structs_8h.html#structpre__pop__info__table__t',1,'']]],
  ['pre_5ftrace_5ft',['pre_trace_t',['../timing__recurrent__pre__stochastic__impl_8h.html#structpre__trace__t',1,'']]],
  ['print_5fsynapse_5fparameters',['print_synapse_parameters',['../synapses_8c.html#a74c97ada7fedd1b5e90ed09797072c29',1,'synapses.c']]],
  ['process_5ffast_5fsource',['process_fast_source',['../spike__source__poisson_8c.html#a8c0f1543e08e9c0d5ea8ac638f65fdac',1,'spike_source_poisson.c']]],
  ['process_5ffixed_5fsynapses',['process_fixed_synapses',['../synapses_8c.html#acfa2aa93ceae2bfe1f57cbd66a30c130',1,'synapses.c']]],
  ['process_5fslow_5fsource',['process_slow_source',['../spike__source__poisson_8c.html#ae6b1e1c0aee533b40075573aca35b72f',1,'spike_source_poisson.c']]],
  ['profile_5ftags_2eh',['profile_tags.h',['../spike__source_2poisson_2profile__tags_8h.html',1,'']]],
  ['profile_5ftags_2eh',['profile_tags.h',['../neuron_2profile__tags_8h.html',1,'']]]
];
