var searchData=
[
  ['sample_5fparams_1993',['sample_params',['http://spinnakermanchester.github.io/SpiNNFrontEndCommon/c/fec.tag/chip__power__monitor_8c.html',1,'']]],
  ['sark_5fdata_1994',['sark_data',['http://spinnakermanchester.github.io/spinnaker_tools/sark_8h.html',1,'']]],
  ['sark_5fvec_1995',['sark_vec',['http://spinnakermanchester.github.io/spinnaker_tools/sark_8h.html',1,'']]],
  ['sdp_5fdata_5fout_5ft_1996',['sdp_data_out_t',['http://spinnakermanchester.github.io/SpiNNFrontEndCommon/c/fec.tag/extra__monitor__support_8c.html',1,'']]],
  ['sdp_5fhdr_1997',['sdp_hdr',['http://spinnakermanchester.github.io/spinnaker_tools/sark_8h.html',1,'']]],
  ['sdp_5fmsg_1998',['sdp_msg',['http://spinnakermanchester.github.io/spinnaker_tools/sark_8h.html',1,'']]],
  ['sdp_5fmsg_5fout_5fpayload_5ft_1999',['sdp_msg_out_payload_t',['http://spinnakermanchester.github.io/SpiNNFrontEndCommon/c/fec.tag/data__speed__up__packet__gatherer_8c.html',1,'']]],
  ['sdp_5fmsg_5fpure_5fdata_2000',['sdp_msg_pure_data',['http://spinnakermanchester.github.io/SpiNNFrontEndCommon/c/fec.tag/sdp__no__scp_8h.html',1,'']]],
  ['sdram_5fblock_2001',['sdram_block',['http://spinnakermanchester.github.io/SpiNNFrontEndCommon/c/fec.tag/malloc__extras_8h.html',1,'']]],
  ['simulation_5fconfig_2002',['simulation_config',['http://spinnakermanchester.github.io/SpiNNFrontEndCommon/c/fec.tag/simulation_8h.html',1,'']]],
  ['simulation_5fprovenance_2003',['simulation_provenance',['http://spinnakermanchester.github.io/SpiNNFrontEndCommon/c/fec.tag/simulation_8h.html',1,'']]],
  ['sorted_5fbit_5ffields_5ft_2004',['sorted_bit_fields_t',['http://spinnakermanchester.github.io/SpiNNFrontEndCommon/c/fec.tag/compressor__sorter__structs_8h.html',1,'']]],
  ['source_5finfo_2005',['source_info',['../spike__source__poisson_8c.html#structsource__info',1,'']]],
  ['spike_5fsource_5ft_2006',['spike_source_t',['../spike__source__poisson_8c.html#structspike__source__t',1,'']]],
  ['srom_5fdata_2007',['srom_data',['http://spinnakermanchester.github.io/spinnaker_tools/sark_8h.html',1,'']]],
  ['stdp_5fparams_2008',['stdp_params',['../synapse__dynamics__stdp__mad__impl_8c.html#structstdp__params',1,'']]],
  ['sv_2009',['sv',['http://spinnakermanchester.github.io/spinnaker_tools/sark_8h.html',1,'']]],
  ['synapse_5fparam_5ft_2010',['synapse_param_t',['../synapse__types__semd__impl_8h.html#structsynapse__param__t',1,'']]],
  ['synapse_5frow_5fplastic_5fdata_5ft_2011',['synapse_row_plastic_data_t',['../synapse__dynamics__stdp__mad__impl_8c.html#structsynapse__row__plastic__data__t',1,'']]]
];
