APP = delay_extension_receiver
BUILD_DIR = build/
SOURCES = delay_extension_receiver.c delay_block.c
APP_OUTPUT_DIR := ../../spinn_front_end_common/connection_builder/connection_builder_app/

include ./Makefile.common
