APP = $(notdir $(CURDIR))

MEANFIELD_MODEL = $(MEANFIELD_DIR)/meanfield/models/meanfield_model_impl.c
MEANFIELD_MODEL_H = $(MEANFIELD_DIR)/meanfield/models/meanfield_model_impl.h
CONFIG_H = $(MEANFIELD_DIR)/meanfield/models/config.h
INPUT_TYPE_H = $(MEANFIELD_DIR)/meanfield/input_types/input_type_conductance.h
MATHSBOX_H = $(MEANFIELD_DIR)/meanfield/models/mathsbox.h
MEANFIELD_IMPL_H = $(MEANFIELD_DIR)/meanfield/implementations/meanfield_impl_standard.h
THRESHOLD_TYPE_H = $(MEANFIELD_DIR)/meanfield/threshold_types/threshold_type_static.h
SYNAPSE_TYPE_H = $(MEANFIELD_DIR)/meanfield/synapse_types/synapse_types_exponential_impl.h
SYNAPSE_DYNAMICS = $(MEANFIELD_DIR)/meanfield/plasticity/synapse_dynamics_static_impl.c

include ../meanfield_build.mk
