PYNN_APP = connection_builder

# Build object list
PYNN_SOURCES = ../connection_builder.cpp \
	../connector_generator.cpp \
	../matrix_generator.cpp \
	../param_generator.cpp \
	../kernel_maths.cpp

RIG_CPP_COMMON_SOURCES = rig_cpp_common/config.cpp \
	rig_cpp_common/maths/normal.cpp \
	rig_cpp_common/maths/ln.cpp \
	rig_cpp_common/maths/exp.cpp \
	rig_cpp_common/maths/hypergeometric.cpp \
	rig_cpp_common/maths/binomial.cpp \
	rig_cpp_common/maths/recip.cpp \
	rig_cpp_common/maths/logfact.cpp

CFLAGS += -I $(CURDIR)

include ../Makefile.common
#

