# Copyright (c) 2017-2019 The University of Manchester
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

"""
Synfirechain-like example
"""
# general imports
from p8_integration_tests.scripts.synfire_run import SynfireRunner
from p8_integration_tests.base_test_case import BaseTestCase
import spynnaker.spike_checker as spike_checker
from spinnman.exceptions import SpinnmanTimeoutException
from unittest import SkipTest

n_neurons = 10  # number of neurons in each population
runtime = 50
synfire_run = SynfireRunner()


class TestGsyn(BaseTestCase):
    """
    tests the printing of get gsyn given a simulation
    """

    def test_get_gsyn(self):
        try:
            synfire_run.do_run(
                n_neurons, max_delay=14.4, time_step=0.1,
                neurons_per_core=5, delay=1.7, run_times=[runtime])

            spikes = synfire_run.get_output_pop_spikes_numpy()
            # no check of spikes length as the system overloads
            spike_checker.synfire_spike_checker(spikes, n_neurons)
            # no check of gsyn as the system overloads
        # System intentional overload so may error
        except SpinnmanTimeoutException as ex:
            raise SkipTest() from ex


if __name__ == '__main__':
    # plotting stuff delay import so unittestsz do not need them
    import matplotlib.pyplot as plt
    from pyNN.utility.plotting import Figure
    from spynnaker.spynnaker_plotting import SpynnakerPanel

    synfire_run.do_run(
        n_neurons, max_delay=14.4, time_step=0.1, neurons_per_core=5,
        delay=1.7, run_times=[runtime])
    gsyn_exc_neo = synfire_run.get_output_pop_gsyn_exc_neo()
    v_neo = synfire_run.get_output_pop_voltage_neo()
    spikes_neo = synfire_run.get_output_pop_spikes_neo()

    Figure(SpynnakerPanel(spikes_neo, yticks=True, xticks=True, markersize=4,
                          xlim=(0, runtime)),
           SpynnakerPanel(v_neo, yticks=True, xticks=True),
           SpynnakerPanel(gsyn_exc_neo, yticks=True),
           title="TestGsyn",
           annotations="generated by {}".format(__file__))
    plt.show()
