APP = $(notdir $(CURDIR))

MEANFIELD_MODEL_H = $(MEANFIELD_DIR)/meanfield_fixing/models/meanfield_model.h
MEANFIELD_MODEL_IMPL = $(MEANFIELD_DIR)/meanfield_fixing/models/meanfield_model_impl.c
MEANFIELD_MODEL_IMPL_H = $(MEANFIELD_DIR)/meanfield_fixing/models/meanfield_model_impl.h
CONFIG_H = $(MEANFIELD_DIR)/meanfield_fixing/models/config.h
SYNAPSE_TYPE_H = $(MEANFIELD_DIR)/meanfield_fixing/synapse_types/synapse_types_exponential_impl.h
INPUT_TYPE_H = $(MEANFIELD_DIR)/meanfield_fixing/input_types/input_type_none.h
MATHSBOX_H = $(MEANFIELD_DIR)/meanfield_fixing/models/mathsbox.h
MEANFIELD_IMPL_STD_H = $(MEANFIELD_DIR)/meanfield_fixing/implementations/meanfield_impl_standard.h
THRESHOLD_TYPE_H = $(MEANFIELD_DIR)/meanfield_fixing/threshold_types/threshold_type_none.h
SYNAPSE_TYPE_H = $(MEANFIELD_DIR)/meanfield_fixing/synapse_types/synapse_types_exponential_impl.h
SYNAPSE_DYNAMICS = $(MEANFIELD_DIR)/meanfield_fixing/plasticity/synapse_dynamics_static_impl.c

include ../meanfield_build.mk
