APP = $(notdir $(CURDIR))

OTHER_SOURCES = $(NEURON_DIR)/neuron/models/neuron_model_patch_clamped_impl.c
NEURON_IMPL_H = $(NEURON_DIR)/neuron/implementations/neuron_impl_generic_ion_channel.h
SYNAPSE_DYNAMICS = $(NEURON_DIR)/neuron/plasticity/synapse_dynamics_static_impl.c

include ../neural_build.mk
