APP = $(notdir $(CURDIR))$(EXT)
SOURCE_DIR = $(NEURAL_MODELLING_DIRS)/src/neuron
MODEL_OBJS = $(SOURCE_DIR)/models/izh_curr.o $(SOURCE_DIR)/static_synapses.o
NEURON_MODEL_H = ../../models/izh_curr.h
SYNAPSE_SHAPING_H = ../../synapses/delta_impl.h

include ../Makefile.common
