APP = $(notdir $(CURDIR))$(EXT)
MODEL_OBJS = ../../models/izh_curr.o ../../static_synapses.o
NEURON_MODEL_H = ../../models/izh_curr.h
SYNAPSE_SHAPING_H = ../../synapses/delta_impl.h

include ../Makefile.common
