// Profiler tags
#ifndef _PROFILE_TAGS_H_
#define _PROFILE_TAGS_H_

#define PROFILER_TIMER                    0
#define PROFILER_SETUP_DMA                1
#define PROFILER_INCOMING_SPIKE           2
#define PROFILER_PROCESS_FIXED_SYNAPSES   3
#define PROFILER_PROCESS_PLASTIC_SYNAPSES 4
#define PROFILER_TIMER_NEURON_UPDATE      5
#define PROFILER_TIMER_SYNAPSES_UPDATE    6
#define PROFILER_DMA_SETUP_TO_CALLBACK    7
#define PROFILER_DMA_CALLBACK             8
#define PROFILER_POP_TABLE_GET_FIRST      9
#define PROFILER_POP_TABLE_GET_NEXT      10

#endif // _PROFILE_TAGS_H_
