APP = $(notdir $(CURDIR))
BUILD_DIR = build/

OTHER_SOURCES = $(SOURCE_DIR)/neuron/models/neuron_model_lif_impl.c
NEURON_IMPL_H = $(SOURCE_DIR)/neuron/implementations/neuron_impl_semd.h
SYNAPSE_DYNAMICS = $(SOURCE_DIR)/neuron/plasticity/synapse_dynamics_static_impl.c

include ../common_custom.mk
