#ifndef _CONSTANTS_H_
#define _CONSTANTS_H_

//! definitions of input components magic numbers
#define INPUT_CONDUCTANCE_COMPONENT_MAGIC_NUMBER 0xAA1
#define INPUT_CURRENT_COMPONENT_MAGIC_NUMBER 0xAA2

//! model components magic numbers
#define MODEL_COMPONENT_INTEGRATE_AND_FIRE_MAGIC_NUMBER 0xAB1
#define MODEL_COMPONENT_IZHIKEVICH_MAGIC_NUMBER 0xAB2

//! synapse shaping magic numbers
#define SYNAPSE_SHAPING_ALPHA_MAGIC_NUMBER 0xAC1
#define SYNAPSE_SHAPING_DELTA_MAGIC_NUMBER 0xAC2
#define SYNAPSE_SHAPING_EXP_MAGIC_NUMBER 0xAC3
#define SYNAPSE_SHAPING_DUEL_EXP_MAGIC_NUMBER 0xAC4

//! c main magic numbers
#define NEURON_MAGIC_NUMBER 0xAD0
#define DELAY_MAGIC_NUMBER 0xAD1
#define SPIKE_SOURCE_POISSON_MAGIC_NUMBER 0xAD2

//! master pop table magic numbers
#define MASTER_POP_2DARRAY_MAGIC_NUMBER 0xBB1
#define MASTER_POP_BINARY_SEARCH_MAGIC_NUMBER 0xBB2
#define MASTER_POP_HASH_TABLE_MAGIC_NUMBER 0xBB3

//! time dependancies magic numbers
#define TIME_DEPENDENCY_PFISTER_SPIKE_TRIPLET_MAGIC_NUMBER 0xCC1
#define TIME_DEPENDENCY_SPIKE_PAIR_MAGIC_NUMBER 0xCC2
#define TIME_DEPENDENCY_SPIKE_NEAREST_PAIR_MAGIC_NUMBER 0xCC3

//! weight dependancies magic numbers
#define WEIGHT_DEPENDENCY_ADDITIVE_MAGIC_NUMBER 0xDD1
#define WEIGHT_DEPENDENCY_ADDITIVE_TWO_TERM_MAGIC_NUMBER 0xDD3
#define WEIGHT_DEPENDENCY_MULTIPLICATIVE_MAGIC_NUMBER 0xDD2

//! synapse structure magic numbers
#define SYNAPSE_PLASTIC_STRUCTURE_WEIGHT_CONTROL 0xEE1
#define SYNAPSE_PLASTIC_STRUCTURE_WEIGHT 0xEE2

//! synapse dynamics magic numbers
#define SYNAPSE_DYNAMICS_STDP 0xFF1
#define SYNAPSE_DYNAMICS_STDP_MAD 0xFF2
#define SYNAPSE_DYNAMICS_STATIC 0xFF3

#endif // _CONSTANTS_H_