APP = $(notdir $(CURDIR))
BUILD_DIR = build/

MODEL_PATH = $(SOURCE_DIRS)/neuron/models/neuron_model_lif_cond_impl
SYNAPSE_TYPE_PATH = ../../synapse_types/synapse_types_exponential_impl
SYNAPSE_DYNAMICS_PATH =  $(SOURCE_DIRS)/neuron/plasticity/synapse_dynamics_static_impl

USES_STDP = FALSE

include ../Makefile.common
