APP = $(notdir $(CURDIR))
BUILD_DIR = build/
MODEL_OBJS = $(SOURCE_DIRS)/neuron/models/neuron_model_lif_cond_impl.o $(SOURCE_DIRS)/neuron/plasticity/synapse_dynamics_static_impl.o
NEURON_MODEL_H = ../../models/neuron_model_lif_cond_impl.h
SYNAPSE_TYPE_H = ../../synapse_types/synapse_types_exponential_impl.h
APPLICATION_MAGIC_NUMBER = 0xAC7

include ../Makefile.common
